In [2]:
import HANEmotionAnalyze
import torch
import torch.nn as nn
import numpy
import time, math
import torch.utils.data as data
import os
import pandas as pd
import json

In [40]:
# import torch.functional as F
# 
embedding = nn.Embedding(10, 3)
input = torch.LongTensor([[0, 1,2,4,5],[1, 4,3,2,9]])
print(embedding(input))
embedding2 = nn.Embedding(10, 3, padding_idx=2)
# input = torch.LongTensor([[1,2,0,5, 6,7,8,9]])
print(embedding2(input))
weight = torch.FloatTensor([[1, 2.3, 3], [4, 5.1, 6.3]])
embedding3 = nn.Embedding.from_pretrained(weight)
input = torch.LongTensor([1])
print(embedding3(input))
input = torch.LongTensor([0])
print(embedding3(input))

tensor([[[-1.5965, -0.9941, -1.0904],
         [-1.4114,  0.0909,  0.0148],
         [ 0.2988, -0.1281,  0.6925],
         [-0.0844, -0.1438, -0.2450],
         [ 1.0504,  0.0801,  0.0100]],

        [[-1.4114,  0.0909,  0.0148],
         [-0.0844, -0.1438, -0.2450],
         [-1.3671,  0.0224, -0.5346],
         [ 0.2988, -0.1281,  0.6925],
         [ 0.9043,  1.6222,  0.1734]]], grad_fn=<EmbeddingBackward>)
tensor([[[ 0.4042,  0.2497,  0.0539],
         [-1.0418,  1.9081, -0.5941],
         [ 0.0000,  0.0000,  0.0000],
         [-1.3613, -0.4405,  1.8863],
         [ 0.0070, -0.1125,  0.9169]],

        [[-1.0418,  1.9081, -0.5941],
         [-1.3613, -0.4405,  1.8863],
         [ 1.1158,  0.7866, -0.4034],
         [ 0.0000,  0.0000,  0.0000],
         [ 0.0027, -2.0208,  0.3357]]], grad_fn=<EmbeddingBackward>)
tensor([[4.0000, 5.1000, 6.3000]])
tensor([[1.0000, 2.3000, 3.0000]])


In [2]:
# num_embeddings, embedding_dim = 5845, 200
# embed = nn.Embedding(num_embeddings, embedding_dim, 0)
# one = torch.from_numpy(numpy.arange(1,10))
# embed(one)

RuntimeError: Expected tensor for argument #1 'indices' to have scalar type Long; but got torch.IntTensor instead (while checking arguments for embedding)

In [ ]:

# def isNan(a):
#     return a != a

# class RatingData4Bert(data.Dataset):
#     def __init__(self, path, tokenizer:Tokenizer, max_row = -1, trainTestRate = 0.85, isTrain = True):
#         self.token_list = []
#         self.label_list = []
#         self.token_positions = torch.tensor([i for i in range(100)])
# 
#         print('地址不应该包含 ratings.csv   path:',path) # 地址不应该包含 ratings.csv
# 
#         ratings_clean_filename = os.path.join(path, 'ratings_clean.csv')
#         ratings_filename = os.path.join(path, 'ratings.csv')
#         if os.path.isfile(ratings_clean_filename):
#             clean_pd = pd.read_csv(ratings_clean_filename)
#         else:
#             print('没有找到缓存的文件%s, 读取源文件%s'%(ratings_clean_filename, ratings_filename))
#             ratings_pd = pd.read_csv(ratings_filename)
#             print('开始生成缓存文件%s'%(ratings_clean_filename))
#             clean_pd = pd.DataFrame({
#                 'userId':[],
#                 'restId':[],
#                 'rating':[],
#                 'comment':[],
#             })
#             nonRatingCount = 0
#             for i, row in ratings_pd.iterrows():
#                 if max_row != -1 and i > max_row:
#                     break
#                 if not isinstance(row['comment'], str) or row['comment'] == '':
#                     # print(i + 1, row['comment'])
#                     nonRatingCount += 1
#                     continue
#                 r0 = row['rating']
#                 r1 = row['rating_env']
#                 r2 = row['rating_flavor']
#                 r3 = row['rating_service']
#                 if r0 == '' or isNan(r0): r0 = 0 # 假设总评分为 0 表示未评分
#                 if r1 == '' or isNan(r1): r1 = 3
#                 if r2 == '' or isNan(r2): r2 = 3
#                 if r3 == '' or isNan(r3): r3 = 3
#                 r0 = round(r0 * 0.5 + (r1 + r2 + r3) * 0.1666666)
#                 if i % 10000 == 9999:
#                     print(i + 1, r0)
# 
#                 token = tokenizer.encode(text=str(row['comment']), max_length=100, pad_to_max_length = True)
#                 # print('token', token)
#                 # token = [101] + token + [102]
# 
#                 newRow = DotDict()
#                 newRow.userId = [row['userId']]
#                 newRow.restId = [row['restId']]
#                 newRow.rating = [r0]
#                 newRow.comment = [json.dumps(token)]
# 
#                 clean_pd = clean_pd.append(pd.DataFrame(newRow), ignore_index=True)
#             print('空的评论数量： %d'%(nonRatingCount))
#             clean_pd.to_csv(ratings_clean_filename)
# 
#         # 读取
#         if isTrain:
#             temp_pd = clean_pd[ : int(len(clean_pd) * trainTestRate)]
#         else:
#             temp_pd = clean_pd[int(len(clean_pd) * trainTestRate) : ]
# 
#         for i, row in temp_pd.iterrows():
#             if max_row != -1 and i > max_row:
#                 break
# 
#             self.label_list.append(torch.tensor(row['rating']).long())
#             self.token_list.append(torch.from_numpy(numpy.array( json.loads(row['comment']) ) ).long())
# 
#     def __getitem__(self, index):
#         # print(self.token_list[index], self.label_list[index], self.token_positions)
#         return self.token_list[index], self.label_list[index], self.token_positions
# 
#     def __len__(self):
#         return len(self.label_list)
    